version: "2.0"

services:

  strapi:
    image: leec121/strapi-blog:0.1
    expose:
      - port: 1337
        as: 80
        to:
          - global: true
        accept:
          - strapi.icp123.org

profiles:
  compute:
    strapi-profile:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 2Gi

  placement:
    akash:
      attributes:
        host: akash
      pricing:
        strapi-profile:
          denom: uakt
          amount: 1000

deployment:
  strapi:
    akash:
      profile: strapi-profile
      count: 1